# Generated by Django 3.1.2 on 2021-06-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_auto_20210623_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='images'),
        ),
    ]
