# Generated by Django 3.1.2 on 2021-07-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_auto_20210628_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='user',
        ),
    ]
