# Generated by Django 3.1.2 on 2021-07-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_auto_20210702_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='author',
        ),
    ]
