# Generated by Django 3.1.2 on 2021-07-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_auto_20210709_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='content',
        ),
    ]
